Components
dazehinn/Math-Magicians pull request #2
Opened 2023-02-23 23:09 UTC by dazehinn

Features in this PR
* I create a new directory called components. 
* I create a calculator component inside the components directory
* I implement the design using only (JSX and CSS)
* I import the calculator component and use it in the top-level component: App.js

2023-02-23 23:25 UTC, GzimAsani requested changes
### Hello, @dazehinn               :wave:   
 Good job so far,  done There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Good job creating the project with create-app :+1: 

 ## Required Changes 

- [ ] In your README file kindly mention running the npm install
- [ ] Check the comments below :arrow_double_down: 

 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-23 23:25 UTC, GzimAsani commented on src/App.css
> +body {
- [ ] All the boilerplate that got created by the CRA (texts, images, and styles) should be deleted, lie the images and logos on public folder

2023-02-23 23:25 UTC, GzimAsani commented on src/components/Calculator.js
> +import React from 'react';
- [ ] According to the requirements Calculator.js should have at least 1 child component

2023-02-23 23:25 UTC, GzimAsani commented on src/components/Calculator.js
> +import './Calculator.css';
- [ ] You do not have a Calculator.css and this is throwing an error, kindly fix it 
![image](https://user-images.githubusercontent.com/62705947/221053705-314a487e-a255-4e7f-bb94-1f2034e029cd.png)

2023-02-23 23:25 UTC, GzimAsani commented on src/App.css
> +  height: 100vh;
- [ ] Kindly fix these borders in order to match the design better 
![image](https://user-images.githubusercontent.com/62705947/221053864-97177b96-f09d-4280-9aa0-e8d123e0b276.png)

2023-02-24 23:15 UTC, ridwanediallo requested changes
# Changes Required ♻️
## Hi @dazehinn, 


![AlmostThereReachGIF](https://user-images.githubusercontent.com/55918904/191301799-36d07166-0e35-4582-a231-7a2d780f7783.gif)

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- GitHub flow is used correctly. ✔
- All linters checks are ok. ✔


 ## Required Changes ♻️

- [ ] Excellent work in implementing some of the changes suggested by the previous reviewer :clap: . However, I believe you have forgotten to remove the boilerplate. Please remove them; not only is it a requirement, but it also gives your project a more professional appearance and makes it easier to navigate. This :point_down:  is what we have so far.
![Screenshot from 2023-02-24 22-40-31](https://user-images.githubusercontent.com/89228743/221314043-98e19412-f511-4644-b7e1-9cfd66bc2779.png)

- [ ] Please in the public folder remove these :point_right:  `logo192.png` `logo512.png` `manifest.json` `robots.txt`.
- [ ] In the src folder remove these :point_right: `App.test.js` `App.css` `index.css` `reportWebVitals.js` `logo.svg`.👌😊


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-24 23:22 UTC, dazehinn commented
@ridwanediallo 
Thanks for pointing out the files to remove. I didn't know exactly which to remove since they all seemed important

2023-02-25 00:00 UTC, ridwanediallo approved these changes
# STATUS: APPROVED 🟢
## Hi @dazehinn, 
![Congratulations!GIF](https://user-images.githubusercontent.com/55918904/191301390-43d62dfa-bfdc-49c5-943b-4d72f4ea5bb8.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- GitHub flow is used correctly. ✔
- Your commit message are good. ✔

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-25 00:13 UTC, merged

2023-02-25 00:29 UTC, dazehinn commented
Oh, @ridwanediallo  it's you still. This is the first time I experience this.